version: '2'
services:
  wordpress:
    build: .
    volumes:
      - ./www:/var/www/html
    env_file: .env
    links:
      - db
      - redis
      - mail
#  cron:
#    build: .
#    command: crond -f -l 6 -L /dev/stdout
#    volumes:
#      - ./wp-content:/var/www/wp-content
#    env_file: .env
#    links:
#      - db
#      - redis
  web:
    image: raulr/nginx-wordpress
    ports:
      - "8080:80"
    links:
      - wordpress
    volumes_from:
      - wordpress
    environment:
      POST_MAX_SIZE: 128m
  db:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
  redis:
    image: redis:3.2.0-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis:/data
  mail:
    image: mailhog/mailhog
    ports:
      - "8082:8025"
  adminer:
    image: adminer
    ports:
      - "8081:8080"
    environment:
      ADMINER_DESIGN: pappu687
volumes:
  db:
  redis:
